#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'aVeryBigSum' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts LONG_INTEGER_ARRAY ar as parameter.
#

def aVeryBigSum():
    sum = 0
    i = 0
    for i in range(0, len(ar)):
        sum += ar[i]
    return sum

n = int(input())
ar = list(map(int, input().split()))
print(aVeryBigSum())
