#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'simpleArraySum' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY ar as parameter.
#

def simpleArraySum(n, ar):
    sum = 0
    i = 0
    for i in range(len(ar)):
        sum += ar[i]
    return sum

n = int(input())
ar = list(map(int, input().split()))
res = simpleArraySum(n, ar)
print(res)














