#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'minimumNumber' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. STRING password
#

def minimumNumber(n, password):
#     # Return the minimum number of characters to make the password strong
#     numbers = "0123456789"
#     lower_case = "abcdefghijklmnopqrstuvwxyz"
#     upper_case = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
#     special_characters = "!@#$%^&*()-+"
#     count = 0
#     if n < 6:
#         return n
#     if any(i.isdigit() for i in password) == False:
#         count += 1
#     if any(i.islower() for i in password) == False:
#         count += 1
#     if any(i.isupper() for i in password) == False:
#         count += 1
#     if any(i in special_characters for i in password) == False:
#         count += 1
#     return max(count, 6-n)
    d = 0
    l = 0
    u = 0
    s = 0
    sp = '!@#$%^&*()-+'
    c = 0
    if n < 6:
            c = 6-n
    ans = 0
    for i in password:
        if i.islower() :
            l += 1
        elif i.isupper():
            u += 1
        elif i in sp:
            s += 1
        elif i.isdigit():
            d += 1
    if s == 0:
        ans += 1
    if d == 0:
        ans += 1
    if u == 0:
        ans += 1
    if l == 0:
        ans += 1
    return max(c,ans)


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    password = input()

    answer = minimumNumber(n, password)

    fptr.write(str(answer) + '\n')

    fptr.close()
